# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.FileField(null=True, upload_to='products/photos/'),
        ),
    ]
