# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190725_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(null=True, upload_to='products/photos/'),
        ),
    ]
